; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeeduino_mega]
platform = atmelavr
board = seeeduino_mega
framework = arduino
extra_scripts = pre:exclude_wiring.py

monitor_speed = 115200

upload_speed = 115200
upload_protocol = stk500v2
