; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:miniatmega328]
platform = atmelavr
board = miniatmega328
framework = arduino
lib_deps = 
	olikraus/U8g2@^2.36.15
	sstaub/LCD-I2C-HD44780@^2.0.3

monitor_speed = 115200
